# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start the server in the background
        run: npm start &

      - name: Wait for the server to start
        run: sleep 10

      - name: Test if the server is running
        run: curl http://localhost:${{ secrets.PORT }} || echo "Server is not running"
