# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "bader" ]
  pull_request:
    branches: [ "bader" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install server dependencies
      run: npm install --prefix server
    - name: Build project (if applicable)
      run: npm run build --if-present --prefix project
    - name: Start Server
      run: |
        nohup npm run start --prefix server &
        sleep 10 # Wait for the server to start
        # Optionally test if the server is running
        curl -f http://localhost:3000 || exit 1
